name: test-and-coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pytest coverage

    - name: Run tests
      run: |
        cd sem2/lab2/test_app.py
        pytest *.py -v

    - name: Generate Report
      run: |
        cd sem2/lab2/test_app.py
        coverage run -m unittest discover -v
        coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
          directory: sem2/lab2/test_app.py
        
